language: java
jdk:
  - openjdk11

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

notifications:
  slack: rkaehdaos:__SLACK_TOKEN__
